theme: jekyll-theme-architect
show_downloads: true
github:
  zip_url: https://github.com/Alword/TreeCalc/archive/1.0.0.zip
  exe_url: https://github.com/Alword/TreeCalc/releases/download/1.0.0/ExpCalc.zip
